### ISSUE TITLE
Warnings in app boot

### ISSUE THREAD

**Issue by kadru** [reidmorrison/rails_semantic_logger#122]
### Environment

* Ruby  2.5.7
* Rails 6.0.3.4
* Semantic Logger 4.7.4
* Rails Semantic Logger 4.5.0
* Puma 5.1.1

`config/application.rb`

```ruby
STDOUT.sync = true
config.rails_semantic_logger.processing = false
config.rails_semantic_logger.add_file_appender = false
config.rails_semantic_logger.format = :json
config.semantic_logger.add_appender(
  io: STDOUT,
  level: config.log_level,
  formatter: config.rails_semantic_logger.format)
```

`config/puma.rb`
```ruby
on_worker_boot do
  # Re-open appenders after forking the process
  SemanticLogger.reopen
end
```

### Expected Behavior

No warnings when is in use with rails and puma.

### Actual Behavior

Warnings: 

```bash
2021-02-15T02:37:25.152238+00:00 app[web.1]: [4] * Listening on http://0.0.0.0:14255
2021-02-15T02:37:25.152293+00:00 app[web.1]: [4] ! WARNING: Detected 2 Thread(s) started in app boot:
2021-02-15T02:37:25.152294+00:00 app[web.1]: [4] ! #<Thread:0x0000562c50117f88@/app/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async.rb:77 sleep_forever> - /app/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async.rb:150:in `pop'
2021-02-15T02:37:25.152352+00:00 app[web.1]: [4] ! #<Thread:0x0000562c51d23f88@/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:334 sleep> - /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:337:in `sleep'

```

**Comment by reidmorrison** [comment]
We run Puma in single mode, so you are on your own with this one. The Semantic Logger thread being created is by design, without it no logging will be performed. Suggest looking into what is generating that warning log message, since it is not from Semantic Logger.

**Comment by reidmorrison** [comment]
I booted our application in clustered mode without any issues. Below is the log output:

~~~
% bin/rails s
=> Booting Rails
=> Booting Puma
=> Rails 6.1.3.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
...
[12175] Puma starting in cluster mode...
[12175] * Puma version: 5.3.2 (ruby 3.0.1-p64) ("Sweetnighter")
[12175] *  Min threads: 5
[12175] *  Max threads: 5
[12175] *  Environment: development
[12175] *   Master PID: 12175
[12175] *      Workers: 2
[12175] *     Restarts: (✔) hot (✔) phased
[12175] * Listening on http://127.0.0.1:3003
[12175] * Listening on http://[::1]:3003
[12175] Use Ctrl-C to stop
[12175] - Worker 0 (PID: 12186) booted in 0.01s, phase: 0
[12175] - Worker 1 (PID: 12187) booted in 0.01s, phase: 0
2021-06-16 20:22:04.182425 D [12186:puma threadpool 002 logger.rb:41] Rack -- Started -- { method: "GET", path: "/", ip: "127.0.0.1" }
...
~~~

As per the docs, just had to add `SemanticLogger.reopen` to the `on_worker_boot` to get logging working.

These are the lines I added / uncommented in `config/puma.yml`
~~~ruby
workers ENV.fetch("WEB_CONCURRENCY") { 2 }

before_fork do
  ApplicationRecord.connection_pool.disconnect! if defined?(ActiveRecord)
end

on_worker_boot do
  ApplicationRecord.establish_connection if defined?(ActiveRecord)

  # Re-open appenders after forking the process
  SemanticLogger.reopen
end
~~~

**Comment by antgel** [comment]
@kadru Did you ever get to the bottom of this? We see something similar.

**Comment by adamk9k** [comment]
@antgel did you get to the bottom of this? Still seeing this with Puma 6 and SemanticLogger configured as per docs

```ruby
on_worker_boot do
  ActiveRecord::Base.establish_connection

  SemanticLogger.reopen
end
```

**Comment by adamk9k** [comment]
I think I managed to replicate this issue by starting the rails app with

```
puma -C config/puma.rb
```

With 
```
rails s
```
it doesn't.

```
 bundle exec rails s
D, [2023-01-23T13:23:54.273813 #11610] DEBUG -- : using default configuration
=> Booting Puma
=> Rails 6.1.7 application starting in development
=> Run `bin/rails server --help` for more startup options

[11610] Puma starting in cluster mode...
[11610] * Puma version: 6.0.0 (ruby 3.1.3-p185) ("Sunflower")
[11610] *  Min threads: 2
[11610] *  Max threads: 2
[11610] *  Environment: development
[11610] *   Master PID: 11610
[11610] *      Workers: 2
[11610] *     Restarts: (✔) hot (✖) phased
[11610] * Preloading application
[11610] * Listening on http://127.0.0.1:5000
[11610] * Listening on http://[::1]:5000
[11610] Use Ctrl-C to stop
[11610] - Worker 0 (PID: 11656) booted in 0.13s, phase: 0
[11610] - Worker 1 (PID: 11657) booted in 0.01s, phase: 0
```


versus

```
puma -C config/puma.rb
[11678] Puma starting in cluster mode...
[11678] * Puma version: 6.0.0 (ruby 3.1.3-p185) ("Sunflower")
[11678] *  Min threads: 2
[11678] *  Max threads: 2
[11678] *  Environment: development
[11678] *   Master PID: 11678
[11678] *      Workers: 2
[11678] *     Restarts: (✔) hot (✖) phased
[11678] * Preloading application
D, [2023-01-23T13:24:32.906538 #11678] DEBUG -- : using default configuration

[11678] * Listening on http://0.0.0.0:5000
[11678] ! WARNING: Detected 1 Thread(s) started in app boot:
[11678] ! #<Thread:0x000000011818b8e8 /usr/local/var/rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/semantic_logger-4.11.0/lib/semantic_logger/appender/async.rb:77 sleep_forever> - /usr/local/var/rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/semantic_logger-4.11.0/lib/semantic_logger/appender/async.rb:150:in `pop'
[11678] Use Ctrl-C to stop
[11678] - Worker 0 (PID: 11728) booted in 0.14s, phase: 0
[11678] - Worker 1 (PID: 11729) booted in 0.02s, phase: 0
```

Note that the Puma config file includes the 

```ruby
on_worker_boot do
  SemanticLogger.reopen
end
```

setting and is loaded by both startup methods, so it seems the initialisation process is somehow different between the two startup methods

cc @reidmorrison
