### ISSUE TITLE
Incompatible with Rails 7.1

### ISSUE THREAD

**Issue by xathien** [reidmorrison/rails_semantic_logger#207]
Rails 7.1 introduced new Broadcast logging, including a `.broadcast_to` command which SemanticLogger doesn't seem to appreciate much.

### Environment
* Ruby Version: 3.1.4
* Semantic Logger Version: 4.14.0
* Rails Version: 7.1
* Rails Semantic Logger Version: Not used
* Rails configuration:
```ruby
ActionController::Base.logger = SemanticLogger["ActionController"]
ActiveRecord::Base.logger = SemanticLogger["ActiveRecord"]
ActionMailer::Base.logger = SemanticLogger["ActionMailer"]
Sidekiq.logger = SemanticLogger["Sidekiq"]

Rails.logger = SemanticLogger["APP"]
```
* Full Stack Trace:
```
/Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.1.0/lib/active_record/railtie.rb:70:in `block in <class:Railtie>': undefined method `broadcast_to' for #<SemanticLogger::Logger:0x00000001159cea30 @filter=nil, @name="APP", @level_index=nil, @level=nil> (NoMethodError)

        Rails.logger.broadcast_to(console)
                    ^^^^^^^^^^^^^
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/railtie.rb:273:in `block in run_console_blocks'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/railtie.rb:298:in `each'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/railtie.rb:298:in `each_registered_block'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/railtie.rb:273:in `run_console_blocks'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/application.rb:586:in `block in run_console_blocks'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/engine/railties.rb:15:in `each'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/engine/railties.rb:15:in `each'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/application.rb:586:in `run_console_blocks'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/engine.rb:449:in `load_console'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/commands/console/console_command.rb:32:in `initialize'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/commands/console/console_command.rb:16:in `new'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/commands/console/console_command.rb:16:in `start'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/commands/console/console_command.rb:106:in `perform'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/command/base.rb:73:in `perform'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/command.rb:71:in `block in invoke'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/command.rb:149:in `with_argv'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/command.rb:69:in `invoke'
	from /Users/xathien/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### Expected Behavior

* I'd sure like to be able to run `rails c` and get a console

### Actual Behavior

* Stacktrace, as above

**Comment by pboling** [comment]
* rails 7.1.3.1
* rails_semantic_logger 4.14.0
* semantic_logger 4.15.0

Trying to understand why most of the documented settings are having no effect, or an unexpected effect.  Some examples:

1. tags are non-sensical:
```
2024-04-05 07:16:15.608812 D [17246:puma srv tp 001] [request_id] [request_id] [ip] [remote_ip] [pathkey] [#<Proc:0x000000010c770378 /Users/pboling/src/apps/my_app/config/application.rb:55 (lambda)>] Rails -- [following-redirect]-----200
```

2. No matter the formatter I choose I get the exact same output, as the default hash:
```
2024-04-05 07:16:16.421403 I [17246:puma srv tp 001] [request_id] [request_id] [ip] [remote_ip] [pathkey] [#<Proc:0x000000010c770378 /Users/pboling/src/apps/my_app/config/application.rb:55 (lambda)>] (10.011s) LandingController -- Completed #index -- { :controller => "LandingController", :action => "index", :params => { "path_key" => "my_path" }, :format => "HTML", :method => "GET", :path => "/my_path", :status => 200, :view_runtime => 283.38, :db_runtime => 26.68, :host => "localhost", :x_forwarded_for => nil, :allocations => 465375, :status_message => "OK" }
```

3. Turning off asset logging has no effect:
```
2024-04-05 07:21:25.088378 I [17246:puma srv tp 002] [request_id] [request_id] [ip] [remote_ip] [pathkey] [#<Proc:0x000000010c770378 /Users/pboling/src/apps/my_app/config/application.rb:55 (lambda)>] Rails -- Started GET "/assets/root/favicon-1464818f1e9ce8573686b0d31b6d977a5a139ff34df99e1379d2bbb289de848e.png" for ::1 at 2024-04-05 07:21:25 +0700
```

**Comment by pboling** [comment]
Probably relevant to this still open issue in Rails 7.1 between tagged logging, log silencer, and broadcast logging:
https://github.com/rails/rails/issues/49745

**Comment by orehmane** [comment]
@pboling did you ever solve the issue where the formatter setting is not respected? I'm running into the same issue on Rails 8.0.2.

**Comment by orehmane** [comment]
Oh, I see, so this is an issue in Rails core that this gem can't address?

**Comment by pboling** [comment]
Broadcast logging and tagged logging, despite being default Rails tools, are not compatible with each other in multiple ways.  It is pretty upgly.  My gems are my attempt to fix it since Rails Core was busy with other stuff.

I am certain that the primary issues are not able to be addressed by this gem without major hacking in Rails Core.

**Comment by reidmorrison** [comment]
Closing this issue as stale, please re-open with any additional information if the issue persists.
